applicative:
test will return 0. and no errror
normal order:
will return error, because first tries to expand expression and (p) call is invalid because function calls itself (infinite loop) applicative (p) call is never evaluated

?????
